INFERENCE:
  preprocess_path: ./datasets/DadaGP-v1.1-preprocessed
  output_path: ./output
  optuna: True
  optuna_trials: 20

TRAIN:
  model: LSTM

  train_scale: 0.8
  val_scale: 0.1
  batch_size: 128

  epochs: 50
  lr: 0.001
