LSTM:
  embedding_size: 256
  hidden_size: 512
  num_layers: 2
  bidirectional: True
  dropout: 0.5

Transformer:
  nhead: 8
  num_encoder_layers: 6
  num_decoder_layers: 6
  d_model: 512
  dim_feedforward: 2048
  dropout: 0.1