LSTM:
  embedding_size:
    TYPE: int
    MIN: 128
    MAX: 512
  hidden_size:
    TYPE: int
    MIN: 256
    MAX: 1024
  num_layers:
    TYPE: int
    MIN: 1
    MAX: 3
  bidirectional:
    TYPE: categorical
    CHOICES: [True, False]
  dropout:
    TYPE: float
    MIN: 0.1
    MAX: 0.5

GRU:
  embedding_size:
      TYPE: int
      MIN: 128
      MAX: 512
  hidden_size:
      TYPE: int
      MIN: 256
      MAX: 1024
  num_layers:
      TYPE: int
      MIN: 1
      MAX: 3
  bidirectional:
      TYPE: categorical
      CHOICES: [True, False]
  dropout:
      TYPE: float
      MIN: 0.1
      MAX: 0.5

Mamba:
  d_model:
    TYPE: int
    MIN: 64
    MAX: 256
  d_state:
    TYPE: int
    MIN: 32
    MAX: 128
  d_conv:
    TYPE: int
    MIN: 4
    MAX: 16
  expand:
    TYPE: int
    MIN: 1
    MAX: 4
  dropout:
    TYPE: float
    MIN: 0.1
    MAX: 0.5